const {chromium}=require('../../jelly-hop/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:5190');await p.waitForFunction(()=>!!window.__komorebi?.getSettings);await p.evaluate(()=>Promise.all([window.__komorebi.environment.ready,window.__komorebi.vegetation.ready]));await p.waitForTimeout(600);
 await p.locator('.elements-toggle').click();assert.equal(await p.locator('[data-setting]').count(),22);
 for(const preset of ['glass','cinematic','playful','natural']){await p.locator('#preset').selectOption(preset);await p.waitForTimeout(80);const s=await p.evaluate(()=>({app:window.__komorebi.getSettings(),field:window.__komorebi.water.waveField.getSettings(),intensity:window.__komorebi.sun.intensity}));assert.equal(s.app.preset,preset);assert.equal(s.field.waveSpeed,s.app.waveSpeed);assert.equal(s.intensity,s.app.sunIntensity);}
 await p.locator('details').evaluateAll(es=>es.forEach(e=>e.open=true));
 const values={stirStrength:1.12,waveSpeed:1.32,waveDamping:1.7,stirRadius:.24,stonePower:.52,stoneSize:.74,throwDuration:.12,splashScale:.45,wind:.31,reflections:.68,clarity:1.4,waterBlue:1.1,sunIntensity:4.1,sunElevation:75,sunAzimuth:-105,exposure:1.12,boatResponse:.7,fishResponse:.8,floatResponse:.9,caustics:.66,sunGlints:1.2,refraction:1.15};
 for(const [key,value]of Object.entries(values)){const input=p.locator(`[data-setting="${key}"]`);await input.fill(String(value));await input.dispatchEvent('input');}
 let s=await p.evaluate(()=>({app:window.__komorebi.getSettings(),field:window.__komorebi.water.waveField.getSettings(),optics:Object.fromEntries(['uReflectionWeight','uCausticStrength','uGlintStrength','uRefractionStrength'].map(k=>[k,window.__komorebi.water.mesh.material.uniforms[k].value])),exposure:window.__komorebi.renderer.toneMappingExposure}));for(const [key,value]of Object.entries(values))assert.equal(s.app[key],value,key);assert.equal(s.app.preset,'custom');assert.equal(s.optics.uCausticStrength,.66);assert.equal(s.optics.uRefractionStrength,1.15);assert.equal(s.field.waveDamping,1.7);assert.equal(s.exposure,1.12);
 await p.screenshot({path:'/tmp/settings-desktop.png'});await p.reload();await p.waitForFunction(()=>!!window.__komorebi);s=await p.evaluate(()=>window.__komorebi.getSettings());for(const [key,value]of Object.entries(values))assert.equal(s[key],value,'reload '+key);
 await p.locator('.elements-toggle').click();await p.locator('.settings-reset-button').click();assert.equal((await p.evaluate(()=>window.__komorebi.getSettings())).preset,'natural');
 await p.locator('.elements-toggle').click();await p.evaluate(()=>{const k=window.__komorebi;k.water.reset();k.water.disturb(2,1,1);window.__cursorAudit=[];const stir=k.water.stirSegment;k.water.stirSegment=(...a)=>{const v=k.camera.position.clone().set(a[2],k.water.heightAt(a[2],a[3]),a[3]).project(k.camera);window.__cursorAudit.push({x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight});return stir(...a);};});
 const points=await p.evaluate(()=>{const k=window.__komorebi;return Array.from({length:25},(_,i)=>{const v=k.camera.position.clone().set(-1+i*.16,k.water.heightAt(-1+i*.16,1),1).project(k.camera);return{x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};});});await p.mouse.move(points[0].x,points[0].y);await p.mouse.down();for(let i=1;i<points.length;i++){await p.mouse.move(points[i].x,points[i].y);await p.waitForTimeout(14);}await p.mouse.up();const audit=await p.evaluate(()=>window.__cursorAudit);assert(audit.length>15);const last=audit.at(-1),requested=points.at(-1);assert(Math.hypot(last.x-requested.x,last.y-requested.y)<1.5,'Source lies under cursor on displaced water');
 await p.setViewportSize({width:390,height:844});await p.locator('.elements-toggle').click();const bounds=await p.locator('.elements-content').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=390);assert(bounds.y+bounds.height<=844);await p.screenshot({path:'/tmp/settings-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS 22 live settings,4 presets,persistence,physical optics/sun controls,mobile panel and cursor-source alignment.');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
