const {chromium}=require('../../jelly-hop/node_modules/playwright');
const sharp=require('../../jelly-hop/node_modules/sharp');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const p=await b.newPage({viewport:{width:1600,height:900},deviceScaleFactor:1});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:5190');await p.waitForFunction(()=>!!window.__komorebi?.stirEffects);await p.evaluate(()=>Promise.all([window.__komorebi.environment.ready,window.__komorebi.vegetation.ready]));await p.waitForTimeout(1200);await p.keyboard.press('h');
 const luminance=async buffer=>{const{data,info}=await sharp(buffer).extract({left:500,top:150,width:600,height:460}).removeAlpha().raw().toBuffer({resolveWithObject:true});let sum=0;for(let i=0;i<data.length;i+=info.channels)sum+=data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722;return sum/(info.width*info.height);};
 const brightness=[];
 for(const value of [0,1,2.2,6]){await p.evaluate(value=>{const k=window.__komorebi;k.water.reset();k.applySettings({...k.getSettings(),waterSunlight:value,wind:0});},value);await p.waitForTimeout(150);const shot=await p.screenshot({path:path.resolve(`captures/sunlight-${value}.png`)});brightness.push(await luminance(shot));}
 assert(brightness[2]>brightness[1]+5,'New default visibly increases water sunlight');assert(brightness[3]>brightness[2]+5,'High sunlight control remains effective');
 await p.evaluate(()=>{const k=window.__komorebi;k.applySettings({...k.getSettings(),waterSunlight:2.2,stirChoppiness:1,wind:.65});k.water.reset();k.stirEffects.reset();window.__cutAudit={spray:0,source:null};const f=k.water.stirSegment;k.water.stirSegment=(...a)=>{if(Math.hypot(a[2]-a[0],a[3]-a[1])>.003)window.__cutAudit.source={x:a[2],z:a[3]};return f(...a);};const tick=()=>{window.__cutAudit.spray=Math.max(window.__cutAudit.spray,k.stirEffects.getState().count);requestAnimationFrame(tick);};requestAnimationFrame(tick);});
 const point=async(x,z)=>p.evaluate(({x,z})=>{const k=window.__komorebi,v=k.camera.position.clone().set(x,k.water.heightAt(x,z),z).project(k.camera);return{x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};},{x,z});const start=await point(-3,1.7);await p.mouse.move(start.x,start.y);await p.mouse.down();for(let i=1;i<=70;i++){const q=await point(-3+i/70*6,1.7);await p.mouse.move(q.x,q.y);await p.waitForTimeout(12);if(i===45)await p.screenshot({path:path.resolve('captures/stir-cut-moving.png')});}
 const result=await p.evaluate(()=>{const k=window.__komorebi,s=window.__cutAudit.source,result={front:k.water.heightAt(s.x+.25,s.z),center:k.water.heightAt(s.x,s.z),field:k.water.waveField.stats(),spray:window.__cutAudit.spray};k.water.endStir();result.lip=result.front-k.water.heightAt(s.x+.25,s.z);result.trough=result.center-k.water.heightAt(s.x,s.z);return result;});assert(result.lip-result.trough>.02,'Moving cursor has a visible leading lip and trough');assert(result.spray>0,'Fast cuts produce fine spray');assert(Math.abs(result.field.mass)<1e-6,'Cut conserves water volume');assert(result.field.maxAbsHeight<.15,'Cut is bounded');await p.screenshot({path:path.resolve('captures/stir-cut-held.png')});await p.mouse.up();await p.waitForTimeout(500);await p.screenshot({path:path.resolve('captures/stir-cut-wake.png')});assert.deepEqual(errors,[]);console.log({status:'PASS',brightness,result,errors});await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
